//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlkemyLabs2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operation
    {
        public int id { get; set; }
        public string name { get; set; }
        public int id_module { get; set; }
    }
}
